language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
- windows
cache:
  cargo: true
script:
- (cd msdfgen-sys && cargo test --release)
- (cd msdfgen-lib && cargo test --release)
- |-
  case $TRAVIS_OS_NAME in
    windows)
      (cd msdfgen && cargo test --release --features ttf-parser,font,png)
      ;;
    *)
      (cd msdfgen && cargo test --release --features all)
      ;;
  esac
jobs:
  allow_failures:
  - rust: nightly
  include:
  - stage: publish
    script:
    - (cd msdfgen-sys && cargo publish || true)
    - (cd msdfgen-lib && cargo publish || true)
    - sleep 10
    - (cd msdfgen && cargo publish || true)
    if: (type = push) && (tag =~ /^\d+\.\d+\.\d+/)
